services:
  demo:
  kml:
    use_grid_names: true
  tms:
    use_grid_names: true
  wms:
    srs: ['EPSG:4326', 'EPSG:3857', 'EPSG:900913']
    image_formats: ['image/jpeg', 'image/png']

layers:
  - name: sec
    title: Sectional Charts
    sources: [sec_cache]

caches:
  sec_cache:
    grids: [webmercator, geodetic]
    sources: [sec_wms]

sources:
  sec_wms:
    type: wms
    req:
      url: http://mapserver/mapserv
      layers: sec
      transparent: true

grids:
  webmercator:
    base: GLOBAL_MERCATOR
  geodetic:
    base: GLOBAL_GEODETIC

globals:
  cache:
    base_dir: /cache
    lock_dir: /cache/locks
